---
####################################################
#          ModuleBuilder Configuration             #
####################################################
CopyPaths:
  - en-US
  - Tests
  - Config
  - tasks
Encoding: UTF8
VersionedOutputDirectory: true
BuiltModuleSubdirectory: builtModule

AliasesToExport:
  - 'Task.Invoke_HQRM_Tests'
  - 'Task.Fail_Build_If_HQRM_Tests_Failed'
  - 'Task.Invoke_HQRM_Tests_Stop_On_Fail'

####################################################
#       Sampler Pipeline Configuration             #
####################################################
BuildWorkflow:
  '.':
    - build
    - test

  DscTest: |
    {
      Import-Module -force DscResource.Test
      Invoke-DscResourceTest -ExcludeTag 'Common Tests - Validate Localization'
    }

  t:
    - build
    - DscTest

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_changelog_release_output

  docs:
    - Generate_Wiki_Content
    - Generate_Conceptual_Help
    - Generate_Markdown_For_Public_Commands
    - Generate_External_Help_File_For_Public_Commands
    - Clean_Markdown_Of_Public_Commands
    - Generate_Wiki_Sidebar
    - Clean_Markdown_Metadata

  pack:
    - build
    #- docs
    - package_module_nupkg

  test:
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  merge:
    - Merge_CodeCoverage_Files

  publish:
    - Publish_Release_To_GitHub
    #- Publish_GitHub_Wiki_Content
    - publish_module_to_gallery

####################################################
#       PESTER  Configuration                      #
####################################################
Pester:
  OutputFormat: NUnitXML
  ExcludeFromCodeCoverage:
    - tasks
    - Template
    - Tests
  Script:
    - tests/QA
    - tests/Unit/
  CodeCoverageThreshold: 60
  CodeCoverageOutputFile: JaCoCo_Merge.xml # the file that is created for each pipeline test job
  CodeCoverageOutputFileEncoding: ascii
  ExcludeTag:
    - helpQuality
    - testQuality
  Tag:
  ExcludeSourceFile:
    - source/potential

CodeCoverage:
  CodeCoverageFilePattern: JaCoCo_Merge.xml # the pattern used to search all pipeline test job artifacts
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml # the file that is created for the merged code coverage

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  DscResource.DocGenerator:
    - 'Task.*'

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: dscbot
  GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false

####################################################
#      DscResource.DocGenerator Configuration      #
####################################################
DscResource.DocGenerator:
  Generate_Conceptual_Help:
    MarkdownCodeRegularExpression:
      - '\`(.+?)\`' # Match inline code-block
      - '\\(\\)' # Match escaped backslash
      - '\[[^\[]+\]\((.+?)\)' # Match markdown URL
      - '_(.+?)_' # Match Italic (underscore)
      - '\*\*(.+?)\*\*' # Match bold
      - '\*(.+?)\*' # Match Italic (asterisk)
  Publish_GitHub_Wiki_Content:
    Debug: true
  Generate_Wiki_Content:
    MofResourceMetadata:
      Type: MofResource
      Category: Resources
    ClassResourceMetadata:
      Type: ClassResource
      Category: Resources
    CompositeResourceMetadata:
      Type: CompositeResource
      Category: Resources
  Generate_Wiki_Sidebar:
    Debug: false
    AlwaysOverwrite: true
